name: Build for Raspberry Pi 64bit

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu # 修改为 64 位目标

      - name: Install Cross-Compilation Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu # 安装 64 位交叉编译器

      - name: Build
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-64bit-binary
          path: target/aarch64-unknown-linux-gnu/release/
